"""Make doc_url not nullable

Revision ID: ac5a1098254f
Revises: 3d4d4f13ff35
Create Date: 2026-01-10 22:19:17.780532

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ac5a1098254f'
down_revision: Union[str, Sequence[str], None] = '3d4d4f13ff35'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('llm_providers', 'doc_url',
               existing_type=sa.TEXT(),
               nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('llm_providers', 'doc_url',
               existing_type=sa.TEXT(),
               nullable=True)
    # ### end Alembic commands ###
