"""Initial schema from existing database

Revision ID: dca23fe4ef31
Revises: 5efce50009d9
Create Date: 2026-01-07 23:13:07.784948

"""

from typing import Sequence, Union

import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "dca23fe4ef31"
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "documents",
        "source_type",
        existing_type=sa.VARCHAR(length=50),
        server_default=None,
        type_=sa.Enum("FILE", "API", "DB", name="sourcetype"),
        existing_nullable=False,
    )
    op.alter_column(
        "documents",
        "updated_at",
        existing_type=postgresql.TIMESTAMP(timezone=True),
        server_default=None,
        nullable=False,
    )
    op.add_column(
        "llm_usage_logs", sa.Column("workflow_run_id", sa.UUID(), nullable=True)
    )
    op.create_foreign_key(
        None,
        "llm_usage_logs",
        "workflow_runs",
        ["workflow_run_id"],
        ["id"],
        ondelete="SET NULL",
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, "llm_usage_logs", type_="foreignkey")
    op.drop_column("llm_usage_logs", "workflow_run_id")
    op.alter_column(
        "documents",
        "updated_at",
        existing_type=postgresql.TIMESTAMP(timezone=True),
        server_default=sa.text("now()"),
        nullable=True,
    )
    op.alter_column(
        "documents",
        "source_type",
        existing_type=sa.Enum("FILE", "API", "DB", name="sourcetype"),
        server_default=sa.text("'FILE'::character varying"),
        type_=sa.VARCHAR(length=50),
        existing_nullable=False,
    )
    # ### end Alembic commands ###
