"""legacy 테이블 제거

Revision ID: e4956fcd7e2b
Revises: 409c2280a1e9
Create Date: 2026-01-13 19:57:47.102826

"""

from typing import Sequence, Union

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "e4956fcd7e2b"
down_revision: Union[str, Sequence[str], None] = "409c2280a1e9"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute("DROP TABLE IF EXISTS legacy_llm_provider CASCADE")
    op.execute("DROP TABLE IF EXISTS legacy_llm_credentials CASCADE")
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
