"""deployment 타입에 schedule 추가

Revision ID: 409c2280a1e9
Revises: ac5a1098254f
Create Date: 2026-01-12 22:36:24.747866

"""

from typing import Sequence, Union

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "409c2280a1e9"
down_revision: Union[str, Sequence[str], None] = "ac5a1098254f"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    op.execute("ALTER TYPE deploymenttype ADD VALUE IF NOT EXISTS 'SCHEDULE'")
    # ### commands auto generated by Alembic - please adjust! ###
    # op.drop_table("legacy_llm_provider")
    # op.drop_table("legacy_llm_credentials")
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # op.create_table(
    #     "legacy_llm_credentials",
    #     sa.Column("id", sa.UUID(), autoincrement=False, nullable=False),
    #     sa.PrimaryKeyConstraint("id", name=op.f("legacy_llm_credentials_pkey")),
    # )
    # op.create_table(
    #     "legacy_llm_provider",
    #     sa.Column("id", sa.UUID(), autoincrement=False, nullable=False),
    #     sa.PrimaryKeyConstraint("id", name=op.f("legacy_llm_provider_pkey")),
    # )
    # ### end Alembic commands ###
